### ISSUE TITLE
Vector vs StridedVector

### ISSUE THREAD

**Issue by milankl** [JuliaApproximation/GenericFFT.jl#15]
Most functions here use `::StridedVector` as argument types, but some use `::Vector` or `::AbstractVector`. It's not fully clear to me whether this actually follows some logic, or whether only parts were gradually abstracted to AbstractVector/StridedVector.

As far as I can see that, most vectors used here need to have implemented
- getindex, setindex!
- length
- real, imag, complex
- and broadcasting, i.e .*, .=

which should apply to much more vectors than just `::Vector`. Raising this as I was trying to use views, i.e. SubArray, which currently isn't supported because of the type constraints.

**Comment by daanhb** [comment]
It may well have been gradual adaption, and I believe that we should enable SubArray's and most AbstractVector's to work. However, it could also be that calls with more generic arguments are intercepted by AbstractFFTs.jl, converted to StridedVector's, and only then routed to our routines - or those of FFTW, which are specific to StridedVector's. We definitely never want to intercept any function call that would have gone to FFTW otherwise in this package.

With that caveat to watch out for, SubArray's should be made to work. Could you post an example that gave you problems?

**Comment by milankl** [comment]
SubArray's do seem to work, but only with `*`
```julia
julia> import GenericFFT, LinearAlgenbra

julia> rfft_plan = GenericFFT.plan_rfft(zeros(Float16,64))
GenericFFT.DummyrFFTPlan{ComplexF16, false, UnitRange{Int64}}(64, 1:1, #undef)

julia> out = rfft_plan*view(randn(Float16,128),1:2:128)
33-element Vector{ComplexF16}:
  Float16(-0.1758) + Float16(0.0)im
   Float16(-2.648) - Float16(8.31)im
    Float16(3.277) - Float16(0.4746)im
    ...
```
and not with `mul!`
```julia
julia> LinearAlgebra.mul!(out,rfft_plan,view(randn(Float16,128),1:2:128))
ERROR: MethodError: no method matching generic_rfft(::SubArray{Float16, 1, Vector{Float16}, Tuple{StepRange{Int64, Int64}}, true}, ::UnitRange{Int64})
Closest candidates are:
  generic_rfft(::Vector{T}, ::Any) where T<:Union{AbstractFloat, Complex{T} where T<:AbstractFloat} at ~/.julia/packages/GenericFFT/Oa0Sx/src/fft.jl:62
Stacktrace:
 [1] mul!(C::Vector{ComplexF16}, p::GenericFFT.DummyrFFTPlan{ComplexF16, false, UnitRange{Int64}}, x::SubArray{Float16, 1, Vector{Float16}, Tuple{StepRange{Int64, Int64}}, true})
   @ GenericFFT ~/.julia/packages/GenericFFT/Oa0Sx/src/fft.jl:262
 [2] top-level scope
   @ REPL[7]:1
```
will check what happens if I change that function signature to `::StridedVector`
