### ISSUE TITLE
Register this package?

### ISSUE THREAD

**Issue by daanhb** [JuliaApproximation/GenericFFT.jl#2]
@dlfivefifty @MikaelSlevinsky any opinions on whether or not to proceed like this?

**Comment by daanhb** [comment]
The code in this package is like that in FastTransforms.jl except that it no longer specializes DSP.conv, in order to reduce the dependencies.
FastTransforms.jl could just use GenericFFT and it would simply still have to define:
```julia
import DSP: conv
conv(u::AbstractArray{T, N}, v::AbstractArray{T, N}) where {T<:AbstractFloat, N} =
    GenericFFT._conv!(deepcopy(u), deepcopy(v))
conv(u::AbstractArray{T, N}, v::AbstractArray{Complex{T}, N}) where {T<:AbstractFloat, N} =
    GenericFFT._conv!(complex(deepcopy(u)), deepcopy(v))
conv(u::AbstractArray{Complex{T}, N}, v::AbstractArray{T, N}) where {T<:AbstractFloat, N} =
    GenericFFT._conv!(deepcopy(u), complex(deepcopy(v)))
conv(u::AbstractArray{Complex{T}, N}, v::AbstractArray{Complex{T}, N}) where {T<:AbstractFloat, N} =
    GenericFFT._conv!(deepcopy(u), deepcopy(v))
```

**Comment by dlfivefifty** [comment]
I’ll defer to @MikaelSlevinsky who wrote the original code… but I’m sure it’s a good idea

**Comment by MikaelSlevinsky** [comment]
Hi @daanhb, thanks for taking charge of this! I would say that registration is good idea.

As for conv, can't remember the last time I used it, but looking at dspbase.jl, maybe a PR there that changes some of the type restrictions on conv would solve a bunch of issues.

For example, the 3-arg (matrix) conv has no type restriction. Since it uses fft and ifft, if GenericFFT were loaded then I think it would just work beyond FFTWNumbers.

This would mean importing DSP in FastTransforms may also be removable.

**Comment by daanhb** [comment]
@JuliaRegistrator register
